import type { Metadata } from 'next'
import { Plus_Jakarta_Sans as PlusJakartaSans } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import { Navbar } from '@/components/navbar'
import Footer from '@/components/footer'

const plusJakartaSans = PlusJakartaSans({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body className={cn('antialiased', plusJakartaSans.className)}>
        <div className="flex min-h-screen flex-col">
          <Navbar />
          <main className="h-full flex-grow">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  )
}
